name: Campingo
description: A new campingo Flutter .

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # add this line to your dependencies
  fluttertoast: ^8.0.9
  flutter:
    sdk: flutter

  get: ^4.1.4
  http: ^0.13.3
  flutter_bloc:
  shared_preferences:
  equatable:
  photo_view: 0.11.1

#  google_fonts: ^2.1.0
  get_storage:
  logger:
  bottom_sheet:
  flutter_staggered_grid_view:
  uuid:
  cached_network_image: ^3.0.0
  flutter_slidable: ^0.6.0
  flutter_card_swipper: ^0.4.0
  clay_containers: 0.3.2
  timeago: ^3.1.0
  auto_size_text:
  dio:
  url_launcher:
#  giffy_dialog: ^1.8.0
  scrollable_positioned_list: 
  carousel_slider: 
  font_awesome_flutter: 
  date_range_picker: ^1.0.5
  cupertino_icons: ^1.0.3
  states_rebuilder: ^6.0.0
  flutter_datetime_picker: ^1.5.1
  flip_card: ^0.6.0
  image_picker: ^0.8.5+1
  syncfusion_flutter_datepicker: ^20.1.52
  datetime_picker_formfield: ^2.0.0
  flutter_rating_bar: ^4.0.1
  animations: ^2.0.2
  intl: ^0.17.0
  flutter_screenutil: ^5.5.3+1
  slide_to_act: ^2.0.1


  # radial_menu: ^0.0.1
  # slider_button: 
  # vibration:
dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^10.1.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.gif"

flutter:
  uses-material-design: true


  assets:
    - assets/imgs/
    - assets/fonts/
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - assets/introduction_animation/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
fonts:
  - family: WorkSans
    fonts:
      - asset: assets/fonts/WorkSans-Regular.ttf
      - asset: assets/fonts/WorkSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/WorkSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/WorkSans-Bold.ttf
        weight: 700
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Bold.ttf
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 400